remote_theme: "mmistakes/minimal-mistakes@4.14.1"
# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

minimal_mistakes_skin: "dark"

title: "Quoc Nguyen"
name: "Quoc Nguyen"

author:
  name             : "Quoc Nguyen"
  avatar           : https://avatars0.githubusercontent.com/u/4478445?s=400&u=f4621902d54989285a7ff9cafeda5a59e5e029c7&v=4
  bio              : "iOS Developer who love to learning new technicals and reading an old books"
  location         : "Osaka, Japan"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:quocnb.vnu@email.com
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://quocnb.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://facebook.com/quocnb.vnu"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/quocnb"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url: "https://instagram.com/"

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

defaults:
  - sope:
      path: ""
      type: home
    values:
      layout: home
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: "Contents"
      toc_sticky: true
